# Generated by Django 2.2.26 on 2022-03-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemateapp', '0002_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Grade',
            field=models.CharField(default='Not yet!', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='PDF',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemateapp.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='coursemateapp.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemateapp.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
