# Generated by Django 2.2.26 on 2022-03-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemateapp', '0015_auto_20220324_1236'),
        ('coursemateapp', '0011_auto_20220324_1310'),
    ]

    operations = [
    ]
